version: '3'
services:

  stress-node-net:
    image: labbsr0x/web-crasher-nodejs
    network_mode: bridge
    build: .
    # volumes:
    #   - $PWD:/var
    #   - $PWD/src:/usr/src/app/src
    environment:
      - HOST=${HOST_IP}:9005
      - TRIGGER_TIME=${TRIGGER_TIME}
      - RUN_INTERVAL=${RUN_INTERVAL}
      - DEBUG=${DEBUG}

  stress-node-http:
    image: labbsr0x/web-crasher-nodejs
    network_mode: bridge
    build: .
    # volumes:
    #   - $PWD:/var
    #   - $PWD/src:/usr/src/app/src
    environment:
      - HOST=${HOST_IP}:9006
      - TRIGGER_TIME=${TRIGGER_TIME}
      - RUN_INTERVAL=${RUN_INTERVAL}
      - DEBUG=${DEBUG}

  stress-node-fastify:
    image: labbsr0x/web-crasher-nodejs
    network_mode: bridge
    build: .
    # volumes:
    #   - $PWD:/var
    #   - $PWD/src:/usr/src/app/src
    environment:
      - HOST=${HOST_IP}:9007
      - TRIGGER_TIME=${TRIGGER_TIME}
      - RUN_INTERVAL=${RUN_INTERVAL}
      - DEBUG=${DEBUG}

  stress-java-spark:
    image: labbsr0x/web-crasher-nodejs
    network_mode: bridge
    build: .
    # volumes:
    #   - $PWD:/var
    #   - $PWD/src:/usr/src/app/src
    environment:
      - HOST=${HOST_IP}:9008
      - TRIGGER_TIME=${TRIGGER_TIME}
      - RUN_INTERVAL=${RUN_INTERVAL}
      - DEBUG=${DEBUG}

  stress-java-nio:
    image: labbsr0x/web-crasher-nodejs
    network_mode: bridge
    build: .
    # volumes:
    #   - $PWD:/var
    #   - $PWD/src:/usr/src/app/src
    environment:
      - HOST=${HOST_IP}:9009
      - TRIGGER_TIME=${TRIGGER_TIME}
      - RUN_INTERVAL=${RUN_INTERVAL}
      - DEBUG=${DEBUG}
